### PR TITLE
Refactor/renaming

### PR DESCRIPTION
**Pull request by ezisazis**
Normalizing the naming convention for the activities and put them under a separated package

Depends on #22

### CODE REVIEW

**Review by sionleroux — CHANGES_REQUESTED** [review]
It is almost impossible to read these diffs because of all of the irrelevant reformatting. It seems your IDE is changing tabs to spaces, could you set it to not do that, and leave the indentation as it is?

**Comment by ezisazis** [comment]
TBH It's only 1 file and if you check the [previous state](https://github.com/sinisterstuf/GuessTheAnimal/blob/master/app/src/main/java/org/sinisterstuf/guesstheanimal/LearnYesNo.java#L41-L65) you can see that it had a wrong identation before.

**Comment by ezisazis** [comment]
Everything else is a diff because I moved a few files under a new package

**Comment by ezisazis** [comment]
Wait 'till #22 is merged, then you can see that there is no real changes in this PR.

**Comment by sionleroux** [comment]
> TBH It's only 1 file
> it had a wrong identation before
> because I moved a few files

Nope, not what I'm talking about. Randomly picked [this snippet of a file](https://github.com/sinisterstuf/GuessTheAnimal/pull/23/commits/c695f7ad449afbb7891cc70964a998b787463c8a#diff-7384a7c32f6d80db4ade996561371f18L34) where 3 times as many lines are diffed than actually have relevant changes because of changing spaces to tabs.

**Comment by sionleroux** [comment]
> Wait 'till #22 is merged

It would be good to be able to merge PRs independently. If you cannot, then they should not be separate PRs. Would these really even have merge conflicts if it weren't for all the white space changes?

**Comment by ezisazis** [comment]
Mmmm you're right, I will check it later.

**Pull request closed without merging**
