### PR TITLE
Use predefined Serilizable name

### PR DESCRIPTION
**Pull request by ezisazis**
In the Guess class there is a duplication of a serilizable name, which can be found in the Animal class, so that's going to be used here too.

### CODE REVIEW

**Comment by sinisterstuf** [comment]
## Danger has errored
[!] Invalid `Dangerfile` file: No such file or directory @ rb_sysopen - app/build/reports/lint/lint-result.xml
```
 #  from Dangerfile:7
 #  -------------------------------------------
 #  # Linting
 >  android_lint.lint
 #  commit_lint.check
 #  -------------------------------------------
```

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Review by sionleroux — APPROVED** [review]
Right!

**Comment by sionleroux** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please rebase to get rid of the merge commits in this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by ezisazis** [comment]
awkward :D

**Comment by sionleroux** [comment]
that was part of an experiment to try resolving conflicts in the GitHub Web UI... apparently never again

**Comment by sionleroux** [comment]
Now I've merged this, but forgot to include the magic words `Merge pull request #33`... this is fun. Closing this PR as its content is already patched into master.

**Pull request closed without merging**
