### PR TITLE
Bump builtToolsVersion to 25.0.2

### PR DESCRIPTION
**Pull request by ezisazis**

### CODE REVIEW

**Comment by sinisterstuf** [comment]
## Danger has errored
[!] Invalid `Dangerfile` file: No such file or directory @ rb_sysopen - app/build/reports/lint/lint-result.xml
```
 #  from Dangerfile:7
 #  -------------------------------------------
 #  # Linting
 >  android_lint.lint
 #  commit_lint.check
 #  -------------------------------------------
```

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by sionleroux** [comment]
So soon? What does 25.0.2 bring us that we didn't have in 25.0.1? :laughing:

**Comment by ezisazis** [comment]
It was 25.0.0 before :P

**Comment by sionleroux** [comment]
Oh, I have 25.0.1 and nothing complained about it. Oh well...

**Review by sionleroux — APPROVED** [review]

**Comment by sionleroux** [comment]
The question still remains though, what does this version bring us above the previous one? (just curious now)

**Comment by ezisazis** [comment]
Probably just some bugfixes. TBH we can go higher 🤔

**Pull request merged**
