### PR TITLE
Ref: Migrate the project to use Gradle build system

### PR DESCRIPTION
**Pull request by ezisazis**
Yoyo @sinisterstuf ! 

I really like yo' work, and I see lots of potential in this project, so I thought maybe I can help you out and contribute into this awesome game! I thought the first step would be great to migrate the project to the well known and used Gradle system. Hope you'll like it! From now on I recommend to use Android Studio for developing. 

Here is the summary after the import:

> 
> ECLIPSE ANDROID PROJECT IMPORT SUMMARY
> ======================================
> 
> Ignored Files:
> --------------
> The following files were *not* copied into the new Gradle project; you
> should evaluate whether these are still needed in your project and if
> so manually move them:
> 
> * .gitignore
> * LICENSE.txt
> * README.md
> * ic_launcher-web.png
> 
> Replaced Jars with Dependencies:
> --------------------------------
> The importer recognized the following .jar files as third party
> libraries and replaced them with Gradle dependencies instead. This has
> the advantage that more explicit version information is known, and the
> libraries can be updated automatically. However, it is possible that
> the .jar file in your project was of an older version than the
> dependency we picked, which could render the project not compileable.
> You can disable the jar replacement in the import wizard and try again:
> 
> android-support-v4.jar => com.android.support:support-v4:18.0.0
> 
> Moved Files:
> ------------
> Android Gradle projects use a different directory structure than ADT
> Eclipse projects. Here's how the projects were restructured:
> 
> * AndroidManifest.xml => app/src/main/AndroidManifest.xml
> * proguard-project.txt => app/proguard-project.txt
> * res/ => app/src/main/res/
> * src/ => app/src/main/java/
> 
> Next Steps:
> -----------
> You can now build the project. The Gradle project needs network
> connectivity to download dependencies.
> 
> Bugs:
> -----
> If for some reason your project does not build, and you determine that
> it is due to a bug or limitation of the Eclipse to Gradle importer,
> please file a bug at http://b.android.com with category
> Component-Tools.
> 
> (This import summary is for your information only, and can be deleted
> after import once you are satisfied with the results.)

Please be aware that I deleted the following files:

-  .gitignore
-  ic_launcher-web.png

### CODE REVIEW

**Comment by sionleroux** [comment]
Awesome! I especially like that stuff moved into `app`, also RIP my jar file. Some questions:

1. does it actually build and run for you like this?
2. why did the PNG have to go?
3. can we please make it so that it uses plain old gradle instead of gradlew wrapper?

**Comment by ezisazis** [comment]
1. Yepp I've tried before sending the PR
2. Is not really used anymore
3. Why do you want to use that? Isn't it easier to just use the wrapped one? Maybe it's more handy on CI system too.

**Comment by sionleroux** [comment]
Easier maybe, but bloat. Why do I have gradle installed on my computer at all if every JVM-related project downloads and runs it individually with gradlew? I think it's pretty ridiculous to install your build tool once for every project on your computer instead of just once.

**Comment by sionleroux** [comment]
tbh I think this worked quite fine with the old build system, but whatever

**Pull request merged**
